### ISSUE TITLE
map_size immediately creates file that large

### ISSUE THREAD

**Issue by patter001** [jnwatson/py-lmdb#85] opened 2015-04-10 20:24 UTC
I'm on windows 8 and it appears that the size specified in the map_size causes a database file to immediately get created at that size. I only file it as an issue since I saw somewhere in the docs that this would happen if I set write_map = True on OSX...But I'm on windows, and I am purposely setting to False to try and avoid the very large file size that I'm specifying "in case" the database grows to be large.

**Comment by dw** [comment] 2015-04-11 13:44
Thanks for the report. Looking at the code, LMDB uses <a href="https://msdn.microsoft.com/en-us/library/windows/desktop/aa365531%28v=vs.85%29.aspx">SetEndOfFile()</a> on Windows, which causes the file to be immediately allocated, regardless of the writemap's setting. That seems to be related to the inability to create a file mapping larger than the underlying disk file on Windows.

Either I can update the docs, or perhaps we can make use of the seemingly undocumented <a href="http://blogs.msdn.com/b/codedebate/archive/2007/12/18/6797175.aspx">FsctlSetSparse</a>. I've poked upstream to figure out if this is a bug or not, and to see if the FsctlSetSparse method has been attempted yet.

**Comment by patter001** [comment] 2015-04-11 21:57
Hi, thanks for checking in on this. If it is upstream in the LMDB code, then I understand not wanting to make a fix that they are not using.  I figured it was at least worth filing in case it was an easy fix or some parameter I could pass in to avoid that behavior. It would be useful to have for sure, but I wouldn't want to cause a divergence from the LMDB source.

**Comment by dw** [comment] 2015-04-11 21:59
Hi there,

There is an experimental patch on https://github.com/dw/py-lmdb/tree/win32-sparse-patch , but I can't provide new .whls since my Windows VM won't boot. If you have access to a working Visual Studio setup, feel free to try this branch, otherwise give me 24 hours.

Chatting with upstream already about getting a reviewed patch for LMDB master branch

**Comment by dw** [comment] 2015-04-11 22:24
Seems I had too much alcohol, wrong IP address :S 

Test wheel/egg builds are available at http://k3.botanicus.net/win32-sparse-patch.dist/ .. please let me know if these work for you.

**Comment by patter001** [comment] 2015-04-11 23:03
Ah yes, that does seem to work. Windows has some odd behavior with showing "size" vs. "size on disk" but I think that more matches what would be expected.

Thanks again for looking in to and fixing!

**Comment by patter001** [comment] 2015-04-12 03:59
FYI: It's hard to be 100% sure, but it looks like there might be a  performance dip in that newer binary...(vs. what is on pypi)  I haven't tried building and running against what is in the master branch yet to see if it is definitely just this change.

**Comment by dw** [comment] 2015-04-12 11:07
Interesting.. the branch does look slower than 0.84. http://k3.botanicus.net/win32-sparse-patch.dist/before.txt http://k3.botanicus.net/win32-sparse-patch.dist/after.txt

The only relevant change in the diff seems to be the sparse patch, I wonder what's happening. dirtybench.py generates a small database that I'd expect to live entirely in RAM and cause no interaction with FS code, but seems that might not be the case.

I also ran the test against an old VM running on a noisy host, so maybe my results are junk

**Comment by dw** [comment] 2015-04-12 11:08
Sorry, forgot to mention, that dirtybench.py script is in the examples directory of the repo

**Comment by patter001** [comment] 2015-04-13 01:17
Yea, I saw about a 15-to-20% loss in my specific test case...bummer. I mostly use the database as read-only, so it would be fine to keep with the larger size...it was just nice to be able see what the used size was so that I could make sure I'm not over doing my map size....ah well. I guess it would be better to stick with the original.

**Comment by dw** [comment] 2015-04-13 08:31
You can use 'python -mlmdb.tool stat -e ...' To view the current number of pages In use, then just multiply by 4kb.

Leaving this ticket open until a working sparse mode is available

**Comment by dw** [comment] 2015-04-20 12:19
Hello again,

I did a little bit of digging, and seems sparse files on Windows are a little more magical than their usual equivalent in UNIX land. The NTFS implementation piggybacks on the same mechanism as compressed files, and subsequently the minimum unit of work is actually quite large – 64kb in the usual case.

You never mentioned if you were using a DB larger than RAM, but if so, this 64kb chunk size might be significantly multiplying the amount of IO required during writes, and potentially reducing resident memory usage efficiency by a much as 16x.

If you're a willing guinea pig, I can supply a build of LMDB+py-lmdb where the LMDB page size has been adjusted to match this chunk size. It may be enough to alleviate or totally eliminate the symptoms you're experiencing.

Alternatively, could you tell me a little about your setup so I can replicate the 20% slowdown locally:

* Is your DB larger than RAM?
* Is the slowdown during read, write, or both?
* Are your reads/writes to ascending key ranges, or random?
* What is the average size of your keys and your values?

Thanks :)

**Comment by patter001** [comment] 2015-04-20 14:49
It definitely fits within memory...Its less than 50 MB...Keys are something like"

"tree#"
"tree#.leaves#"

where there are 5000 tree # each with 10 leaves....

Each one has a dictionary in it that is 20 entries long with each entry being a random string that is 20 characters long..

I was mostly just testing read performance...I turn around and read 2000 of the 5000 I wrote (sequentially...not randomly).

I'm a bit of a newb on contributing back here, let me find some place today where I can easily upload the script I'm using. Its bogus data at this point, I was prototyping a bunch of different data storage solutions....

**Comment by dw** [comment] 2015-04-20 14:57
Well if it's smaller than RAM, then slowdown isn't IO/cache usage :(  So that theory is blown out of the water.

If you want to share script, gist.github.com is handy for that

**Comment by patter001** [comment] 2015-04-20 15:10
Here's the script....Yeah, I goofed and uploaded before logging in.

https://gist.github.com/anonymous/4f9b4307ed23df80e7d4

test2000 is the function for base-lining

**Comment by patter001** [comment] 2015-05-20 15:33
I apologize if this is a silly question or a limitation of lmdb in general:
is it possible to add an option to allow the database to grow past the
mapsize? Since on windows I'm pretty much forced to have a file the same
size as the mapsize ?

Even with the applied patch, if I copy the database, the new file ends up
the full size of the map.

**Comment by woozzu** [comment] 2015-09-16 08:26
@patter001 I modified win32-sparse-patch of @dw.

https://github.com/woozzu/py-lmdb/tree/win32-sparse-patch

The difference is that db file is first created as sparse file of full mapsize, and when being closed the size shrinks to the actual data size and the sparse file flag is cleared. I did not test the performance yet, but hopefully I think we can take advantage of sparse file property in write mode and no disadvantage remains in read mode after created.

**Comment by dw** [comment] 2015-11-30 18:54
Hi there,

Upstream has produced a new patch that uses internal Windows APIs to create a memory mapped file that can be grown on demand. Is this issue still affecting anybody? If so, I can produce Windows binaries for you to try out.

Would be great to get feedback on performance and reliability of the patch

**Comment by dw** [comment] 2015-11-30 18:55
The relevant diff is here: https://github.com/LMDB/lmdb/commit/fb5a768a77ca5330e15a3a34ceb694bc11cb216a

**Comment by patter001** [comment] 2015-12-01 00:03
I am definitely intrigued...I'm currently working OK with my workarounds,
but if you end up creating something, I will try to run some regressions
against it (but it may take me a day or two).

**Comment by dw** [comment] 2015-12-02 14:45
Hi there,

I've built binaries for Python 2.7 x32 and x64 available at http://k3.botanicus.net/tmp/lmdb/

A cursory test suggests the binaries work fine, though I'm not sure about performance. If you have any other Python version you'd like to test just let me know and I'll build binaries for them.

**Comment by patter001** [comment] 2015-12-10 12:46
Sorry for such a long delay. .. this is a pretty awesome little patch!
Read Performance looked about the same with my initial checkout. But my
database creation seemed to get a 33% boost -- Probably because in my use
case I was constantly re-mapping the DB when it was too small...My DB is
actually much smaller too..not sure what was up with that, maybe I had some
lurking bug in my constant remapping :-)  but either way, size seems to
have gotten much better as well.

It is awesome that I can simply set it to simply be a full out 1G and hit a
variety of use cases vs. sometimes the DB is 6MB and sometimes it was 500MB
and having the performance hits of managing that...man...overall, this
patch seems like a big jump forward for me.

Thank You!

**Comment by dw** [comment] 2015-12-10 12:53
Thanks for the testing. Hyc is looking to get the patch into LMDB's stable branch, after which I'll cut a new py-lmdb release that includes it. Will close this ticket when that is all done.

**Comment by patter001** [comment] 2015-12-10 13:12
Actually...I did hit some odd issue where i can't open the DB
"readonly=True" anymore...I don't think that matters much to my usecase,
but just throwing it out there.

**Comment by dw** [comment] 2015-12-10 13:22
The readonly=True problem is fixed on mdb.master. Would you like me to cut new testing eggs or are you happy to wait until the next py-lmdb release? Thanks again!

**Comment by patter001** [comment] 2015-12-11 13:17
I am fine waiting for the next release. Thanks!

**Comment by patter001** [comment] 2016-02-05 22:48
Man, hopefully I'm not doing something stupid and wasting your time, but I saw that there was a new 0.88 release. So I tried out the large map size and I see my file immediate start off at that size. It was definitely working in the test build you gave out earlier, so I went back to confirm whether I had user error but those were gone....Do you see this feature working on windows now, and I'm just having some user error?

**Comment by dw** [comment] 2016-02-05 23:23
Hi again,

This patch is to mdb.master, py-lmdb is currently tracking the LMDB release branch. I've already asked upstream about getting the patch merged over, will try asking again, but it might be simpler for you to just stick to the custom build in the meantime (or I can investigate turning it into an install-time option if that's easier for you)

Thanks, and sorry for the confusion :)

**Comment by patter001** [comment] 2016-02-06 01:00
Ah ok, thanks. Yeah, I can wait a bit longer.   I would't want to get away
from the main release.

**Comment by patter001** [comment] 2016-02-22 14:42
I hate to back away from my "I can wait longer" so soon, but I keep hitting
snags here and there were this would be a huge benefit. I went to build the
win32-master, but I hit some issues during the link phase for "NtClose",
"NtMapViewOfSection" and "NtCreateSection". Does that happen to ring any
bells?

**Comment by dw** [comment] 2016-02-22 14:55
It does indeed :(  Those functions are only exposed in the Windows driver development kit (DDK). But I did not install it for the build, instead I generated a synthetic .LIB (for KERNEL32.DLL IIRC) containing references only to those exact functions.

This is actually incredibly fiddly to get right -- I wasted quite some time on it. Would you like me to rebase win32-master and then try to fix up setup.py to handle this stuff for you? Sorry none of this stuff was automated yet, I was waiting to see if we could get the patch on mdb.RE before bothering

**Comment by dw** [comment] 2016-02-22 14:55
Rough instructions for creating the .LIB are here: https://web.archive.org/web/20130330132630/http://www.coderetard.com/2009/01/21/generate-a-lib-from-a-dll-with-visual-studio

**Comment by patter001** [comment] 2016-02-22 16:15
Perfect! Thanks! Yes, with that info and a slight mod to setup.py I was
able to get the build to occur. Thanks again!

**Comment by patter001** [comment] 2016-11-09 22:14
I was just curious if the upstream ever did a release with the feature that solved the issue of immediately creating the file the size of the DB?

**Comment by dw** [comment] 2016-11-09 23:35
Hey there,

So since December 2015 when we last chatted about this, mdb.RE has gone into feature freeze, and the patch can't be cherry-picked across to the release branch any more.

mdb.master isn't likely to see a release candidate before January 2017.

As a workaround, I'm happy to look at providing a separate "lmdb_master" package with binary wheels on Windows, since that package would also occasionally be useful in UNIX land too. What do you think?

**Comment by patter001** [comment] 2016-11-10 12:47
Sounds like quite it might be a bit open ended as to when they would have a
release would be open to pick this up. I wonder if there was some reason it
didn't make the release that I should be concerned about...?

A new lmdb_master python module sounds excellent! I hope others would find
useful as well. The py-lmdb has been a great tool. A lmdb_master module
where we don't have to manually resize should help a ton with getting
multi-processing going and bump up our performance a bit.

**Comment by dw** [comment] 2016-11-15 00:23
@patter001 this is still a WIP, maybe another few days, and while I've been working on it I've become less convinced mdb.master is the right target. I'm thinking of resurrecting the old mdb.RE+sparse patch branch I made last year.

Basically the problem is that I haven't a clue what is in mdb.master, and upstream are likely to say "go away" if we hit any issues :)  So cherry-picking just the sparse file patch and releasing that as a separate "lmdb_win32" package probably makes much more sense.

**Comment by patter001** [comment] 2016-11-15 01:48
:-) Yeah, I was afraid of that about the upstream too. I appreciate you
looking in to this again. If you spun a release with this patch that would
be awesome. If that's a bit of hassle, I can keep with redistributing the
modified version from that old patch -- but I admit an lmdb_win32 released
on pypi would be great so I could reference folks to that.

**Closed** 2020-07-27 14:18 UTC

**Comment by patter001** [comment] 2020-07-27 15:59
Just as FYI since this is closed and I see the other reference issue is closed:

We are still using the previous version that you built that worked around the issue on windows and that has been doing fine for the last few years.  So far we have not seen any issues there on windows, so thank you very much for that initial patch.   The changes impacted  Linux, so we use your proposed solution in Windows and on Linux we use the default lmdb distro.

**Comment by BenisonSam** [comment] 2020-09-12 23:39
Is there any working solution for this on Windows?

**Comment by jnwatson** [comment] 2020-09-14 03:20
No. Still waiting on an upstream release.

**Comment by shenck0** [comment] 2022-06-05 00:47
This bug still exists on lmdb1.3.0 (Python3.8.3+Windows10)

**Comment by krpatter-intc** [comment] 2023-02-19 00:13
I use the old branch you created. And it may be that you still prefer to keep this out of main, but I though it may be helpful to others to bring the branch close to what the HEAD has.

https://github.com/jnwatson/py-lmdb/pull/338
